###
POST http://localhost:8000/api/book/
Content-Type: application/json

{
  "title": "clean code"
}

###

GET http://localhost:8000/api/book/c6757b8e-78ea-4a97-9207-276d6024680d
Content-Type: application/json